import Head from 'next/head'
import Image from 'next/image'
import { makeStyles } from '@mui/styles'
import Link from 'next/link'

const useStyles = makeStyles(theme => ({
  container: {
    padding: '0 2rem',
    backgroundImage: `linear-gradient(to bottom, ${theme.palette.yellow.secondary}, #FFFFFF)`
  },
  
  main: {
    minHeight: '100vh',
    padding: '4rem 0',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  header: {
    display: 'flex',
    flex: 1,
    padding: '2rem 0',
    borderTtop: '1px solid #ebd6d6',
    justifyContent: 'left',
    alignItems: 'center',
  },

  headerLink: {
    // display: 'flex',
    // justifyContent: 'right',
    // flexGrow: 1,
    margin: 0,
    lineHeight: 1.15,
    fontSize: '1.5rem',
    letterSpacing: '4px',
    display: 'flex',
    textAlign: 'center',
    alignItems: 'center',
    fontWeight: 'bold'
    // '&:hover': {
    //   textDecoration: 'underline'
    // },
  },
  
  footer: {
    display: 'flex',
    flex: 1,
    padding: '2rem 0',
    borderTop: '1px solid #eaeaea',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  footerLink: {
    // display: 'flex',
    // justifyContent: 'center',
    // flexGrow: 1,
    alignItems: 'center',
    '&:hover': {
      textDecoration: 'underline'
    },
  },
  
  title: {
    margin: 0,
    lineHeight: 1.15,
    fontSize: '4rem',
    letterSpacing: '8px',
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
  },
  
  description: {
    margin: '4rem 0',
    lineHeight: 1.5,
    fontSize: '1.5rem',
    textAlign: 'center',
  },
  
  logo: {
    verticalAlign: 'middle',
  },
}));

export default function About() {
  const classes = useStyles();

  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            rel="preload"
            href="/fonts/RopaSans/RopaSans-Regular.ttf"
            as="font"
            crossOrigin=""
          />
      </Head>

      <header className={classes.header}>
        <Image src="/Logo.svg" alt="Sinagpala Logo" width={36} height={36} className={classes.logo}/>
        <Link href="/">
          <a
            className={classes.headerLink}
          >
            Sinagpala
          </a>
        </Link>
      </header>

      <main className={classes.main}>
        <h1 className={classes.title} >
          <Image style="vertical-align:middle" src="/Logo.svg" alt="Sinagpala Logo" width={150} height={150} />
          Sinagpala
        </h1>

        <p className={classes.description}>
        About us content here.
        </p>

        <a href="https://nextjs.org/docs" >
            <p>Explore Marikina Area</p>
        </a>

      </main>

      <footer className={classes.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className={classes.footerLink}
        >
          Powered by{' '}
          <span className={classes.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
