import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { makeStyles } from '@mui/styles'
import Header from '../components/header'
import Footer from '../components/footer'
import NoSsr from '../components/NoSsr'
import data from './api/marikinaBounds/marikina_polygon_bounds.json'
import Button from '@mui/material/Button'
import Box from '@mui/material/Box'
import dynamic from 'next/dynamic'  
import Typography from '@mui/material/Typography'

const LinePlot = dynamic(() => import("../components/line-plot"), {
  loading: () => "Loading...",
  ssr: false
});

const useStyles = makeStyles(theme => ({
  container: {
    padding: '0 2rem',
    backgroundImage: `linear-gradient(to bottom, ${theme.palette.yellow.secondary}, #FFFFFF)`
  },
  main: {
    minHeight: '90vh',
    padding: '3rem 0',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    lineHeight: 1.15,
    letterSpacing: '8px',
    display: 'flex',
    alignItems: 'center',
  },
  logo: {
    verticalAlign: 'middle',
  },
  dataRow: {
    display: 'flex',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    alignItems: 'center',
    width: '80%',
    margin: '2rem 0',
    textAlign: 'center',
  },
  dataColumn: {
    display: 'flex',
    justifyContent: 'center',
    textAlign: 'center',
    padding: '1rem'
  },
  infoBlock: {
    fontSize: '30px',
  },
  dataBlock: {
    fontSize: '60px',
    color: theme.palette.orange.main,
    fontWeight: 'bold',
  },
  imgBound: {
    margin: '100px'
  }
}));

function Item(props) {
  const { sx, ...other } = props;
  const classes = useStyles();
  return (
    <Box
      sx={{
        ...sx,
      }} 
      className={classes.dataRow}
      {...other}
    />
  )
}

export default function Home({ data }) {
  const classes = useStyles();
  const marikina_data = data.properties;
  console.log(marikina_data)
  return (
    <NoSsr>
      <div className={classes.container}>
        <Head>
          <title>Sinagpala</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" type="image/png" 
          href="../public/logo.svg" />
          <link
              rel="preload"
              href="/fonts/Ropa_Sans/RopaSans-Regular.ttf"
              as="font"
              crossOrigin=""
            />
        </Head>
        <Header />

        <main className={classes.main}>
          <Item>
            <Typography variant="h1" className={classes.title} >
              <Image src="/Logo.svg" alt="Sinagpala Logo" width={150} height={150} className={classes.logo}/>
              Sinagpala
            </Typography>
          </Item>

          <Item>
            <Typography variant="h6" lassName={classes.centerText}>
              Have your rooftops checked for its solar energy potential.
            </Typography>
          </Item>

          <Item>
            <Button variant="outlined">
              <Link href="/explore">
                  <a href="https://nextjs.org/docs" >
                      <p>Explore Marikina Area</p>
                  </a>
              </Link>
            </Button>
          </Item>

          <Item>
            <Typography variant="h3" lassName={classes.centerText}>
              Did You Know?
            </Typography>
          </Item>

          <Item>
            <Image src="/marikina_bounds.png" alt="Sinagpala Logo" width={550} height={550} className={classes.imgBound}/>
            <div className={classes.dataColumn}>
              <div className={classes.infoBlock}> 
                Marikina has an estimated {<br />}
                potential of having {<br />} 
                <span className={classes.dataBlock}>
                  {marikina_data['total_kwh']}
                </span> kWh {<br />}
                of solar energy
              </div>
            </div>
          </Item>

          <Item>
            <LinePlot data={{properties:marikina_data}} type="hour" />
          </Item>
        </main>

        {/* <Footer /> */}
      </div>
    </NoSsr>
  )
}

export async function getStaticProps(){
  return {
    props: {
      data: data.features[0],
    },
  }
}

